### ISSUE TITLE
Serious limitations trying to mimic schema.org hierarchy with Doctrine ORM inheritance

### ISSUE THREAD

**Issue by teohhanhui** [dunglas/api-platform#6]
Consider this scenario:

```
// src/AppBundle/Entity/Thing.php
namespace AppBundle\Entity;

use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Dunglas\ApiBundle\Annotation\Iri;

/**
 * The most generic type of item.
 *
 * @see http://schema.org/Thing Documentation on Schema.org
 *
 * @ORM\MappedSuperclass
 * @Iri("http://schema.org/Thing")
 */
abstract class Thing
{
    /**
     * @var Collection<ImageObject> An image of the item. This can be a [URL](http://schema.org/URL) or a fully described [ImageObject](http://schema.org/ImageObject).
     *
     * @ORM\ManyToMany(targetEntity="ImageObject")
     * @Iri("http://schema.org/image")
     */
    private $image;
}
```

```
// src/AppBundle/Entity/ImageObject.php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Dunglas\ApiBundle\Annotation\Iri;

/**
 * An image file.
 *
 * @see http://schema.org/ImageObject Documentation on Schema.org
 *
 * @ORM\Entity
 * @Iri("http://schema.org/ImageObject")
 */
class ImageObject extends MediaObject
{
}
```

(CreativeWork and MediaObject omitted for brevity)

This breaks down whenever there's more than one entity extending from Thing (well, of course...)

**Comment by teohhanhui** [comment]
> Many-To-Many associations are only possible if the mapped superclass is only used in exactly one entity at the moment

http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html

**Comment by dunglas** [comment]
Your example should work because the image association refers to `ImageObject` not to `Thing`.

**Comment by teohhanhui** [comment]
Let me illustrate by using this repo (api-platform) itself. This is what I get when I run `app/console doctrine:schema:validate` right out of the box (after composer install, of course).

```
[Mapping]  FAIL - The entity-class 'AppBundle\Entity\CreativeWork' mapping is invalid:
* The referenced column name 'id' has to be a primary key column on the target entity class 'AppBundle\Entity\CreativeWork'.
* The join columns of the many-to-many table 'creativework_person' have to contain to ALL identifier columns of the source entity 'AppBundle\Entity\CreativeWork', however '' are missing.
```

**Comment by dunglas** [comment]
Yes I'm aware of that warning, however it works. IMO here it's the Doctrine validator command that is faulty. Can you upload somewhere a repo with an example that doesn't work?

**Comment by teohhanhui** [comment]
Thanks for the reassurance.

**Comment by dunglas** [comment]
What was the problem (for future search on the same issue)?

**Comment by teohhanhui** [comment]
Please see the issue-6 branch in my fork.

This is what I get when running `app/console doctrine:schema:update`:

```
  [Doctrine\DBAL\Schema\SchemaException]                            
  The table with name 'tripviss.thing_imageobject' already exists.
```

**Comment by dunglas** [comment]
Try to reset your database:

    app/console doctrine:database:drop
    app/console doctrine:database:create
    app/console doctrine:schema:create

**Comment by teohhanhui** [comment]
@dunglas FYI my database is empty. The issue is with Doctrine not being smart enough to generate one join table per mapped entity.

**Comment by dunglas** [comment]
Ok I got it. So you need to override the mapping for each child entity and override the generated class name.
IMO it's not the responsibility of the generator to handle such cases but any work on this (a patch to Doctrine or a new doc entry) is welcome.

**Comment by dunglas** [comment]
After further reading, it looks like a Doctrine Schema generator bug. As Mapped Superclasses are not entities, the generator should name correctly (like names you suggested) the generated tables.

Can you open an issue on the Doctrine bug tracker?

**Comment by teohhanhui** [comment]
I have doubts whether it's supposed to work in the first place:

https://github.com/doctrine/doctrine2/blob/v2.5.0/tests/Doctrine/Tests/ORM/Mapping/AnnotationDriverTest.php#L137

**Comment by teohhanhui** [comment]
From @beberlei's comment on http://www.doctrine-project.org/jira/si/jira.issueviews:issue-html/DDC-945/DDC-945.html
> ... unidirectional Many To Many associations work if you use the Mapped Superclass only once ...
For 2.1 there will be an additional feature described in DDC-964 that allows overriding certain mapped superclass details to avoid these problems.

**Comment by dunglas** [comment]
So it seems to work now by overriding the table name in the child class: https://github.com/doctrine/doctrine2/commit/0a09a28ec9301b371da54babb076df84a0d2033f

**Comment by csarrazi** [comment]
Yup. You should use [@AssociationOverride](http://doctrine-orm.readthedocs.org/en/latest/reference/inheritance-mapping.html#association-override), to specify the correct table name.

**Comment by suryacaprice** [comment]
@dunglas docker-compose exec app vendor/bin/schema in this command i always get the error app does not exist .
how to generate from yaml file ? can you post a video on youtube so that it will be a quick stat for every on on how to generate a ORM model

**Comment by dunglas** [comment]
(This component isn't mandatory, you create your model by yourself too).

Can you post your YAML file and the error you get please?

**Comment by suryacaprice** [comment]
User:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    contact_number:
      type: integer
      length: 10
      nullable: true

docker-compose exec app vendor/bin/schema
ERROR: No such service: app

**Comment by dunglas** [comment]
You probably use 2.2. `docker-compose exec php vendor/bin/schema`

**Comment by suryacaprice** [comment]
I am using 2.2.1 .. you want me to go down to 2.2.0 . Is there any major changes in 2.2.1 thats not in 2.2.0 ?

**Comment by dunglas** [comment]
The docs was outdated, see https://github.com/api-platform/docs/pull/402

**Comment by suryacaprice** [comment]
docker-compose exec php vendor/bin/schema
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"vendor/bin/schema\": stat vendor/bin/schema: no such file or directory": unknown
